using System.Text;
using Microsoft.Xna.Framework.Input;

namespace HenrySolidAdventure.Controller
{
    internal static class InputController
    {
        [System.Runtime.InteropServices.DllImport("user32.dll")]
        private static extern long GetKeyboardLayoutName(
          StringBuilder pwszKlid);
        private static KeyboardState Keyboard => Microsoft.Xna.Framework.Input.Keyboard.GetState();
        internal static bool LeftInput { get; private set; }
        internal static bool RightInput { get; private set; }
        internal static bool JumpInput { get; private set; }
        internal static bool ShiftInput { get; private set; }
        internal static bool InteractInput { get; private set; }
        internal static bool InventoryInput { get; private set; }
        internal static bool Attack { get; private set; }
        internal static bool Block { get; private set; }
        internal static bool ExitInput { get; private set; }

        internal static void Update()
        {
            StringBuilder name = new StringBuilder(9);
            GetKeyboardLayoutName(name);
            string layout = name.ToString();

            //get arrow inputs first
            LeftInput = Keyboard.IsKeyDown(Keys.Left);
            RightInput = Keyboard.IsKeyDown(Keys.Right);
            JumpInput = Keyboard.IsKeyDown(Keys.Up) || Keyboard.IsKeyDown(Keys.Space);

            if (layout == "00000409")//querty
            {
                LeftInput = LeftInput ? LeftInput : Keyboard.IsKeyDown(Keys.A);
                Attack = Keyboard.IsKeyDown(Keys.Q);
                JumpInput = JumpInput ? JumpInput : Keyboard.IsKeyDown(Keys.W);

            }
            else//azerty
            {
                LeftInput = LeftInput ? LeftInput : Keyboard.IsKeyDown(Keys.Q);
                Attack = Keyboard.IsKeyDown(Keys.A);
                JumpInput = JumpInput ? JumpInput : Keyboard.IsKeyDown(Keys.Z);
            }
            //non-layout dependant generated by github copilot

            RightInput = RightInput ? RightInput : Keyboard.IsKeyDown(Keys.D);
            InteractInput = Keyboard.IsKeyDown(Keys.F) || Keyboard.IsKeyDown(Keys.Enter);
            Block = Keyboard.IsKeyDown(Keys.E);
            ShiftInput = Keyboard.IsKeyDown(Keys.LeftShift) || Keyboard.IsKeyDown(Keys.RightShift);
            ExitInput = Keyboard.IsKeyDown(Keys.Escape);
            InventoryInput = Keyboard.IsKeyDown(Keys.I);
        }
    }
}
